logging:
  level:
    root: info
    org.springframework.r2dbc: debug

spring:
  profiles:
    active: dev
  application:
    name: oauth2
  r2dbc:
    url: r2dbc:postgresql://172.16.8.102:5432/oauth2
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  redis:
    host: 172.16.8.102
    port: 6379